Name : Arpit Agarwal
Roll no. : 102303347
Batch : 3C25

Assignment 1 - Based On NumPy

Q1: Questions on Basic NumPy Array

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [76]:
import numpy as np
a = np.array([1, 2, 3, 6, 4, 5])
reversed_a = np.flip(a)
reversed_a

array([5, 4, 6, 3, 2, 1])

(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods


In [77]:
    import numpy as np
    arr = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
    flattened_arr = arr.flatten()
    flattened_arr

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

(c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [78]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
result = (arr1 == arr2)
result

array([[ True,  True],
       [ True,  True]])

(d) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

In [79]:
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])
count = np.bincount(x)
most_freq_value = np.argmax(count)
indices = np.where(x == most_freq_value)[0]
print("Most frequent value:", most_freq_value)
print("Indices:", indices)

Most frequent value: 1
Indices: [0 5 7 8 9]


ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [80]:
import numpy as np
y = np.array([1,1,1,2,3,4,2,4,3,3])
count = np.bincount(y)
most_freq_value = np.argmax(count)
indices = np.where(y == most_freq_value)[0]
print("Most frequent value:", most_freq_value)
print("Indices:", indices)

Most frequent value: 1
Indices: [0 1 2]


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find

i. Sum of all elements

In [81]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
total_sum = np.sum(gfg)
total_sum

np.int64(45)

ii. Sum of all elements row-wise

In [82]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
row_sum = np.sum(gfg, axis=1)
row_sum

matrix([[14],
        [16],
        [15]])

In [83]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
col_sum = np.sum(gfg, axis=0)
col_sum

matrix([[20,  9, 16]])

(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

i. Sum of diagonal elements

In [84]:
import numpy as np
n_array = np.array([[55, 25, 15],
                    [30, 44,  2],
                    [11, 45, 77]])
diagonal_sum = np.trace(n_array)
diagonal_sum

np.int64(176)

ii. Eigen values of matrix

In [85]:
import numpy as np
n_array = np.array([[55, 25, 15],
                    [30, 44,  2],
                    [11, 45, 77]])
eigenvalues = np.linalg.eigvals(n_array)
eigenvalues

array([98.16835147, 28.097044  , 49.73460452])

iii. Eigen vectors of matrix

In [86]:
import numpy as np
n_array = np.array([[55, 25, 15],
                    [30, 44,  2],
                    [11, 45, 77]])
eigenvectors = np.linalg.eig(n_array)
eigenvectors

EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))

iv. Inverse of matrix

In [87]:
import numpy as np
n_array = np.array([[55, 25, 15],
                    [30, 44,  2],
                    [11, 45, 77]])
inverse_matrix = np.linalg.inv(n_array)
inverse_matrix

array([[ 0.02404141, -0.00911212, -0.00444671],
       [-0.01667882,  0.02966905,  0.0024785 ],
       [ 0.00631287, -0.01603732,  0.01217379]])

v. Determinant of matrix

In [88]:
import numpy as np
n_array = np.array([[55, 25, 15],
                    [30, 44,  2],
                    [11, 45, 77]])
determinant = np.linalg.det(n_array)
determinant

np.float64(137180.0000000001)

(g) Multiply the following matrices and also find covariance between matrices using NumPy:

i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]

In [89]:
import numpy as np
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
product1 = np.matmul(p1, q1)
cov1 = np.cov(p1.flatten(), q1.flatten())
print("i. Matrix Multiplication:\n", product1)
print("i. Covariance matrix:\n", cov1)

i. Matrix Multiplication:
 [[16 19]
 [26 31]]
i. Covariance matrix:
 [[0.66666667 1.        ]
 [1.         1.66666667]]


ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

In [90]:
import numpy as np
p1 = np.array([[1, 2], [2, 3],[4,5]])
q1 = np.array([[4,5,1],[6,7,2]])
product1 = np.matmul(p1, q1)
cov1 = np.cov(p1.flatten(), q1.flatten())
print("ii. Matrix Multiplication:\n", product1)
print("ii. Covariance matrix:\n", cov1)

ii. Matrix Multiplication:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
ii. Covariance matrix:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [91]:
import numpy as np
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner_product = np.inner(x, y)
print("Inner product:\n", inner_product)
outer_product = np.outer(x, y)
print("Outer product:\n", outer_product)
from itertools import product
cartesian_product = np.array([np.concatenate((a, b)) for a, b in product(x, y)])
print("Cartesian product (row-wise combinations):\n", cartesian_product)

Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product (row-wise combinations):
 [[ 2  3  4  1  5  0]
 [ 2  3  4  5 10  3]
 [ 3  2  9  1  5  0]
 [ 3  2  9  5 10  3]]


Q2: Based on NumPy Mathematics and Statistics

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Find element-wise absolute value
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.
iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

In [92]:
import numpy as np
array = np.array([[1, -2, 3],
                  [-4, 5, -6]])
abs_array = np.abs(array)
print("i. Absolute values:\n", abs_array)

percentiles_flat = np.percentile(array, [25, 50, 75])
percentiles_cols = np.percentile(array, [25, 50, 75], axis=0)
percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)
print("ii. Percentiles of flattened array (25th, 50th, 75th):", percentiles_flat)
print("\nPercentiles per column:\n", percentiles_cols)
print("\nPercentiles per row:\n", percentiles_rows)

mean_flat = np.mean(array)
median_flat = np.median(array)
std_flat = np.std(array)
mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)
mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

print("iii. Mean (flattened):", mean_flat)
print("Median (flattened):", median_flat)
print("Std Dev (flattened):", std_flat)
print("\nMean per column:", mean_col)
print("Median per column:", median_col)
print("Std Dev per column:", std_col)
print("\nMean per row:", mean_row)
print("Median per row:", median_row)
print("Std Dev per row:", std_row)


i. Absolute values:
 [[1 2 3]
 [4 5 6]]
ii. Percentiles of flattened array (25th, 50th, 75th): [-3.5 -0.5  2.5]

Percentiles per column:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]

Percentiles per row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
iii. Mean (flattened): -0.5
Median (flattened): -0.5
Std Dev (flattened): 3.8622100754188224

Mean per column: [-1.5  1.5 -1.5]
Median per column: [-1.5  1.5 -1.5]
Std Dev per column: [2.5 3.5 4.5]

Mean per row: [ 0.66666667 -1.66666667]
Median per row: [ 1. -4.]
Std Dev per row: [2.05480467 4.78423336]


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [93]:
import numpy as np
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor_values = np.floor(a)
ceil_values = np.ceil(a)
trunc_values = np.trunc(a)
rounded_values = np.round(a)
print("Original array:     ", a)
print("Floor values:       ", floor_values)
print("Ceiling values:     ", ceil_values)
print("Truncated values:   ", trunc_values)
print("Rounded values:     ", rounded_values)

Original array:      [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]
Floor values:        [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values:      [-1. -1. -0.  1.  2.  2.  3.]
Truncated values:    [-1. -1. -0.  0.  1.  1.  3.]
Rounded values:      [-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i. Sorted array
ii. Indices of sorted array
iii. 4 smallest elements
iv. 5 largest elements

In [94]:
import numpy as np
array_a = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array_a)
print("i. Sorted array:", sorted_array)
sorted_indices = np.argsort(array_a)
print("ii. Indices of sorted array:", sorted_indices)
smallest_4 = sorted_array[:4]
print("iii. 4 smallest elements:", smallest_4)
largest_5 = sorted_array[-5:]
print("iv. 5 largest elements:", largest_5)

i. Sorted array: [ 10  16  16  52  54  62 453]
ii. Indices of sorted array: [0 3 4 1 5 2 6]
iii. 4 smallest elements: [10 16 16 52]
iv. 5 largest elements: [ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
i. Integer elements only
ii. Float elements only

In [95]:
import numpy as np
array_b = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integers_only = array_b[array_b == array_b.astype(int)]
print("i. Integer elements only:", integers_only)
floats_only = array_b[array_b != array_b.astype(int)]
print("ii. Float elements only:", floats_only)

i. Integer elements only: [1. 2. 3. 2.]
ii. Float elements only: [1.2 2.2]


Q4:
(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)

In [96]:
import cv2
import numpy as np

def img_to_array(path, save_as="image_data.txt"):
    # Try reading as a grayscale image
    img_gray = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    if img_gray is not None:
        print("Image is in Grayscale")
        np.savetxt(save_as, img_gray, fmt='%d')
        return img_gray
    
    # Try reading as a color image
    img_rgb = cv2.imread(path, cv2.IMREAD_COLOR)
    if img_rgb is not None:
        print("Image is in RGB")
        # Convert from BGR to RGB
        img_rgb = cv2.cvtColor(img_rgb, cv2.COLOR_BGR2RGB)
        # Save each channel separately
        with open(save_as, 'w') as f:
            for channel, name in zip(cv2.split(img_rgb), ['Red', 'Green', 'Blue']):
                f.write(f"--- {name} Channel ---\n")
                np.savetxt(f, channel, fmt='%d')
                f.write("\n")
        return img_rgb

    raise ValueError("Image not found or unsupported format.")


In [97]:
ml = img_to_array("C:/Users/agarw/Desktop/ML-Lab.jpg")

Image is in Grayscale


(b) Load the saved file into jupyter notebook?

In [98]:
loaded_gray = np.loadtxt("image_data.txt", dtype=int)
print("Loaded Grayscale Image Array:\n", loaded_gray)


Loaded Grayscale Image Array:
 [[52 52 52 ... 52 52 52]
 [52 52 52 ... 52 52 52]
 [52 52 52 ... 52 52 52]
 ...
 [52 52 52 ... 52 52 52]
 [52 52 52 ... 52 52 52]
 [52 52 52 ... 52 52 52]]


In [99]:
with open("image_data.txt", "r") as f:
    content = f.read()

print("Loaded RGB image content from text file:")
print(content)


Loaded RGB image content from text file:
52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 57 57 57 57 57 57 57 57 58 58 58 58 58 58 58 58 57 57 57 56 56 56 55 55 58 58 57 57 57 56 56 56 56 56 56 56 56 56 56 56 58 58 58 58 58 58 58 58 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57